id: P008042
initial_creation_type: ocr
source_metadata:
  id: bdr:W1GS5
  title: ཟུར་མཁར་བའི་ཤེས་བྱའི་ཁོག་འབུགས
  author: ''
  volumes:
    dc480f63816b40a583c0a44723f59300:
      image_group_id: I1PD450
      title: ''
      volume_number: 1
      total_pages: 344
ebook_metadata:
  title: ཟུར་མཁར་བའི་ཤེས་བྱའི་ཁོག་འབུགས
  author: ''
  sku: P008042
  cover: cover.jpg
  layers:
  - pagination
