id: P008042
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:57:28.120067
source_metadata:
  id: bdr:W1GS5
  title: ཟུར་མཁར་བའི་ཤེས་བྱའི་ཁོག་འབུགས
  author: ''
  volumes:
    d0d24a7259df4dcfb16f61a20ad3642e:
      image_group_id: I1PD450
      title: Volume 1 of zur mkhar ba'i shes bya'i khog 'bugs
      volume_number: 1
      total_pages: 344
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
