id: I941EAA2A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T03:38:44+00:00'
last_modified: '2022-06-08T18:01:05.730476+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1GS5
  title: ཟུར་མཁར་བའི་ཤེས་བྱའི་ཁོག་འབུགས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A1D1:
      image_group_id: I1PD450
      title: Volume 1 of zur mkhar ba'i shes bya'i khog 'bugs
      total_pages: 344
      order: 1
      base_file: A1D1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
